# -*- coding: utf-8 -*-
"""Training.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JSGNx7u6PvFk3ehthzcUlVYrMHzHQ1D7
"""

import numpy as np
a=np.array([1,2])
type(a)

a=[1,2,3]
b=[2]
c=a[::-1]
print(c)
print(a[2:])
print(a[:])
print(a[:1])
del a[0]
print(sum(a))
print(a)
print()
def add(alist):
  return sum(alist)
print(add(a))

"""Operation on a List
  * [1,2,3]*2=[1,2,3,1,2,3]
  + Used for concatenation.Can only concatenate lists
  





"""

a=(1,2,3)
a=(1,2,3,4)
print(a)
b=a[::-1]
print(b)
c=("ABC","DEF",1,2)
print(c)
print(type(a[0]))
type(c[0])

d={'a':"abc",'b':123}
type(d)
print(d)

my_int=42
print("original integer: ",my_int)
result=my_int*2
print("result after multiplication is",result)

import random
responses={
    "hours":"From  9 AM to 5 PM Every Monday to Friday",
    "products":"We Offer a variety of products including electronics, clothing and many more",
    "location":"Located in Hyderabad"
}
def chatbot(input):
  input=input.lower()
  if "hours" in input:
     print(responses["hours"])
  elif "products" in input:
    print(responses["products"])
  elif "location" in input:
    print(responses["location"])
  else:
    print("I'm sorry, I didn't understand your question.")

a=input("Enter your question: ")
chatbot(a)

a="hello world"
b=a.upper()
c=a.replace("hello","hi")
d="123xy"

print(d.isdigit())
print(b)
print(a)
print(c)

a=1
b=2
a,b=b,a
print(a,b)

a="python is not fun, Java is Better"
swap=a.swapcase()
print(swap)

a=range(10)
for i in a:
  print(i)

a=[1,2,3,4,5,5,3]
b=[]
for i in range(len(a)):
  for j in range(i+1,len(a)):
    if a[i]==a[j]:
      b.append(a[j])
def abc(b):
  if len(b)>=1:
    return True
  else:
    return False
if abc(b):
  print("It Does")
else:
  print("It doesn't")

def iseven(a):
  if a%2==0:
    return True
  else:
    return False
print(iseven(5))

a= lambda x:x*2
print(a(5))

username="Anil Kumar"
password="Anil@123"
print("Please Enter Your Details")
a=input("Enter Your Username: ")
b=input("Enter Your Password: ")
if a==username and b==password:
  print("Login Successful")
else:
  print("Login Failed")

